spec:
    inputs:
        filename:
            description: "Filename for the submission CSV"
            type: string
            default: default

---
variables:
    SUBMISSION_DIR: "submissions"
    COMPETITION: "march-machine-learning-mania-2025"

stages:
  - lint
  - build
  - submit
  - results

ruff_format:
  stage: lint
  image: astral/uv:python3.12-alpine
  needs: []
  before_script:
    - uv sync --only-group lint --locked
  script:
    - uvx ruff format --check notebooks src

ruff_lint:
  stage: lint
  image: astral/uv:python3.12-alpine
  needs: []
  before_script:
    - uv sync --only-group lint --locked
  script:
    - uvx ruff check src

submit_to_kaggle:
  stage: submit
  image: python:3.12
  when: manual
  before_script:
    - pip install kaggle
    - mkdir -p ~/.kaggle
    - echo "{\"username\":\"${KAGGLE_USERNAME}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
    - chmod 600 ~/.kaggle/kaggle.json
  script:
    - FILE="$SUBMISSION_DIR/$[[ inputs.filename ]]"
    - echo "Submitting $FILE to Kaggle..."
    - kaggle competitions submit -c $COMPETITION -f "$FILE" -m "Automated GitLab submission"


fetch_kaggle_results:
  stage: results
  image: python:3.12
  when: manual
  needs:
    - job: submit_to_kaggle
      optional: true
  before_script:
    - pip install kaggle
    - mkdir -p ~/.kaggle
    - echo "{\"username\":\"${KAGGLE_USERNAME}\",\"key\":\"${KAGGLE_KEY}\"}" > ~/.kaggle/kaggle.json
    - chmod 600 ~/.kaggle/kaggle.json
  script:
    - echo "Fetching submission results from Kaggle..."
    - kaggle competitions submissions -c $COMPETITION > submissions.txt
    - cat submissions.txt
    - echo "Latest submission status:"
    - head -n 2 submissions.txt
  artifacts:
    paths:
      - submissions.txt
    expire_in: 7 days

build_report:
  stage: build
  image: cr.gitlab.switch.ch/hslu/edu/bachelor-computer-science/aicomp/student-repositories/hs25/march-machine-learning-mania-2025-basketball-tournaments/code:latest
  before_script:
    - cd doc
    - mkdir _build
  script:
    - pandoc src/report.md --defaults defaults.yaml -o _build/report.pdf
  artifacts:
    paths:
      - doc/_build/report.pdf
    expire_in: 1 day
