repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format notebooks src
        language: system
        pass_filenames: false

      - id: ruff-check
        name: ruff-check
        entry: uv run ruff check --fix src
        language: system
        pass_filenames: false