[project]
name = "aicomp-mmlm"
version = "0.1.0"
description = "Solving the March Machine Learning Mania 2025 Kaggle competition"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    {name = "Luca Kyburz", email = "luca.kyburz@stud.hslu.ch"},
    {name = "Dave Schurtenberger", email = "david.schurtenberger@stud.hslu.ch"},
]
dependencies = [
    "pandas>=2.3.2",
    "matplotlib>=3.8.0",
    "numpy>=1.26.4",
    "seaborn>=0.13.2",
]

[project.optional-dependencies]
notebooks = [
    "jupyterlab>=4.4.9",
    "notebook>=7.4.7",
]
