from typing import Protocol

import pandas as pd


class BaseDataloader(Protocol):
    def setup(self) -> None: ...
    def train_data(self, prediction_season: int) -> tuple[pd.DataFrame, pd.Series]: ...
    def valid_data(self) -> tuple[pd.DataFrame, pd.Series]: ...
    def test_data(self, df: pd.DataFrame) -> pd.DataFrame: ...
