from collections.abc import Generator
from typing import Protocol

import pandas as pd


class BaseDataloader(Protocol):
    def setup(self) -> None: ...
    def train_data(self, prediction_season: int, start_season: int) -> tuple[pd.DataFrame, pd.Series]: ...
    def valid_data(self) -> tuple[pd.DataFrame, pd.Series]: ...
    def test_data(self, df: pd.DataFrame) -> pd.DataFrame: ...


class EnsembleDataloader(Protocol):
    def setup(self) -> None: ...
    def train_data(
        self, prediction_season: int, start_season: int
    ) -> Generator[tuple[int, tuple[pd.DataFrame, pd.Series], ...], None, None]: ...
    def test_data(self, df: pd.DataFrame) -> pd.DataFrame: ...
