class Columns:
    HIGHER_TEAM = "HigherID"
    ID = "ID"
    LOWER_TEAM = "LowerID"
    PRED = "Pred"
    RESULT = "Result"
    SEASON = "Season"
    TEAM_A = "TeamAID"
    TEAM_B = "TeamBID"
    TEAM_ID = "TeamID"
    SEED = "Seed"
    WTEAM_ID = "WTeamID"
    LTEAM_ID = "LTeamID"
    REGION = "Region"
    DAY_NUM = "DayNum"
    SCORE = "Score"
    WSCORE = f"W{SCORE}"
    LSCORE = f"L{SCORE}"
    WELO = "WElo"
    LELO = "LElo"
    NUM_OT = "NumOT"
    POINT_DIFF = "PointDiff"
    WIN = "Win"
    QUALITY = "Quality"
    WQUALITY = f"W{QUALITY}"
    LQUALITY = f"L{QUALITY}"
    QUALITY_DIFF = f"{QUALITY}Diff"
    WIN_STREAK = "WinStreak"
    LOSS_STREAK = "LossStreak"
    WWIN_STREAK = f"W{WIN_STREAK}"
    WLOSS_STREAK = f"W{LOSS_STREAK}"
    LWIN_STREAK = f"L{WIN_STREAK}"
    LLOSS_STREAK = f"L{LOSS_STREAK}"
    ELO_DELTA = "EloDelta"
    WELO_DELTA = f"W{ELO_DELTA}"
    LELO_DELTA = f"L{ELO_DELTA}"
    # Team identifier columns for feature engineering
    T1_TEAM_ID = "T1_TeamID"
    T2_TEAM_ID = "T2_TeamID"
    TARGET = "Target"
    # Additional columns for data processing
    MEN_WOMEN = "MenWomen"
    WLOC = "WLoc"
    STREAK = "Streak"
    T1_STREAK = "T1_Streak"
    T2_STREAK = "T2_Streak"
    STREAK_DIFF = "StreakDiff"
    ELO = "Elo"
    T1_ELO = "T1_Elo"
    T2_ELO = "T2_Elo"
    ELO_DIFF = "EloDiff"
    ELO_DELTA_DIFF = "EloDeltaDiff"
    T1_SEED = "T1_seed"
    T2_SEED = "T2_seed"
    SEED_DIFF = "SeedDiff"
    T1_QUALITY = "T1_Quality"
    T2_QUALITY = "T2_Quality"
    LAST_ELO = "LastElo"


class Metrics:
    BRIER = "brier"
    TRAIN_BRIER = f"train_{BRIER}"
    VALID_BRIER = f"valid_{BRIER}"
    TRAIN_BRIER_CV_FOLD = f"{TRAIN_BRIER}_cv_fold"
    TRAIN_BRIER_CV_FULL = f"{TRAIN_BRIER}_cv_full"
    FOLD = "fold"
